### PR TITLE
Recommend why functional programming matters

### PR DESCRIPTION
**Pull request by xnning**
Want to recommend the article why functional programming matters.

This is not a scared research paper but rather a modest introduction on how functional programming plays an important role in software development using many interesting examples. It is a quite famous paper that got more than 1k citations and is usually considered a good article to read when understanding the motivation of functional programming.

I checked adding this reference still fits the page.

### CODE REVIEW

**Comment by xnning** [comment]
@googlebot I signed it!

**Review by mihaimaruseac — APPROVED** [review]

**Comment by illia-bobyr** [comment]
This is indeed a good article, but I wonder if all the links will now fit on the slide.
Did you try generating the PDF and checking?

P.S. We should work on a release process %)

**Comment by xnning** [comment]
> This is indeed a good article, but I wonder if all the links will now fit on the slide.
> Did you try generating the PDF and checking?

Yes! You may have missed the description: I checked adding this reference still fits the page :).

**Comment by illia-bobyr** [comment]
> > This is indeed a good article, but I wonder if all the links will now fit on the slide.
> > Did you try generating the PDF and checking?
> 
> Yes! You may have missed the description: I checked adding this reference still fits the page :).

Indeed, I missed it =)
Thanks for checking!

**Pull request merged**
